%%
%% This is file `uqsreport.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% uqsreport.dtx  (with options: `class')
%% 
%% This is where we put the licensing...
%% 
%% File: uqsreport.dtx
\RequirePackage{expl3,xparse}
\ProvidesExplClass{ uqsreport }{ 2020/03/27 }{ 1.0.2 }
  { Technical Report template for use by UQ Space }
%% 
%%
%% End of file `uqsreport.cls'.
