%%
%% This is file `uqsreport.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% uqsreport.dtx  (with options: `class')
%% 
%% This is where we put the licensing...
%% 
%% File: uqsreport.dtx
\RequirePackage{expl3,xparse}
\ProvidesExplClass{ uqsreport }{ 2020/03/27 }{ 1.0.2 }
  { Technical Report template for use by UQ Space }
\RequirePackage [ table, x11names ] { xcolor   }
\RequirePackage [ pagestyles ]      { titlesec }
\RequirePackage                     { titletoc }
\RequirePackage                     { tikz     }
\providecolor { uqspacenavy }{ HTML }{ 0E1F66 }

\colorlet { section       }{ uqspacenavy }
\colorlet { subsection    }{ uqspacenavy }
\colorlet { subsubsection }{ uqspacenavy }
\colorlet { paragraph     }{ uqspacenavy }
%% 
%%
%% End of file `uqsreport.cls'.
